# Este nombre es el identificador del microservicio en Spring Cloud
spring.application.name=msvc-usuarios
server.port=8001

# Para mariaDB se usa esta misma conexion en localhost
# spring.datasource.url=jdbc:mysql://localhost:3306/msvc_usuarios?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=false

# Para mariaDB usamos esta conexion para Docker
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/msvc_usuarios?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=false


spring.datasource.username=root
spring.datasource.password=sasa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Elegir para MariaDB si se usa esta
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuracion importante para que cree una sola vez la tabla. Se creara apartir de la clase @Entity
# Si la tabla ya esta creada no es necesaria esta ocnfiguracion
spring.jpa.generate-ddl=true

# Ver las trazas de ejecucion consultas
logging.level.org.hibernate.SQL=debug

#Configuracion para guardar logs, colocamos ruta de carpeta donde se guardara en el contenedor /app/logs
logging.file.path=/app/logs


